name: practica_2
description: My practica integradora 2 para mi clase de progamacion de dispositivos moviles.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  avatar_glow: ^2.0.2
  bootstrap_icons: ^1.7.2
  flutter_shimmer: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
