// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsVhQHDj5Tcz_gSsdGa9aNi6fE9Nf2kcQ',
    appId: '1:1048757970593:android:11e765b647d8dfb68bf2e0',
    messagingSenderId: '1048757970593',
    projectId: 'practica2-9180b',
    storageBucket: 'practica2-9180b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCT1lgsNCYBFsGYne1_FY_9tG0rKqEB9w',
    appId: '1:1048757970593:ios:c4f7b066c040c84c8bf2e0',
    messagingSenderId: '1048757970593',
    projectId: 'practica2-9180b',
    storageBucket: 'practica2-9180b.appspot.com',
    iosClientId: '1048757970593-pn8k4vj1ab0defo1tm95p2013ukf4k5p.apps.googleusercontent.com',
    iosBundleId: 'com.practica2.gustavosotres',
  );
}
